salesforce-twitter integration task/force-app/main/default/objects/Tweet__c/Tweet__c.object-meta.xml
<CustomObject>
    <label>Tweet</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Tweet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tweets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-twitter integration task/force-app/main/default/objects/Tweet__c/fields/Tweet_Date__c.field-meta.xml
<CustomField>
    <fullName>Tweet_Date__c</fullName>
    <description>Timestamp of when the tweet was posted.</description>
    <label>Tweet Date</label>
    <type>DateTime</type>
</CustomField>

salesforce-twitter integration task/force-app/main/default/objects/Tweet__c/fields/Tweet_ID__c.field-meta.xml
<CustomField>
    <fullName>Tweet_ID__c</fullName>
    <label>Tweet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

salesforce-twitter integration task/force-app/main/default/objects/Tweet__c/fields/Tweet_Text__c.field-meta.xml
<CustomField>
    <fullName>Tweet_Text__c</fullName>
    <label>Tweet Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

salesforce-twitter integration task/force-app/main/default/objects/Tweet__c/fields/Tweet_Title__c.field-meta.xml
<CustomField>
    <fullName>Tweet_Title__c</fullName>
    <label>Tweet Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

salesforce-twitter integration task/force-app/main/default/classes/TweetController.cls
public with sharing class TweetController {
    @AuraEnabled(cacheable=true)
    public static List<Tweet__c> getRecentTweets() {
        return [SELECT Id, Tweet_Title__c, Tweet_Text__c, Tweet_ID__c, Tweet_Date__c, CreatedBy.Name
                FROM Tweet__c 
                WHERE Tweet_Date__c != null
                AND Tweet_Title__c != null
                AND Tweet_Title__c != ''
                ORDER BY Tweet_Date__c DESC 
                LIMIT 5];
    }

    @AuraEnabled(cacheable=true)
    public static List<Tweet__c> getTweetsCreatedByMe() {
        return [SELECT Id, Tweet_Title__c, Tweet_Text__c, Tweet_Date__c, Tweet_ID__c 
                FROM Tweet__c 
                WHERE CreatedById = :UserInfo.getUserId() 
                AND Tweet_Date__c != null
                AND Tweet_Title__c != null
                AND Tweet_Title__c != ''
                ORDER BY Tweet_Date__c DESC];
    }

    @AuraEnabled(cacheable=true)
    public static List<Tweet__c> getAllTweets() {
        return [SELECT Id, Tweet_Title__c, Tweet_Text__c, Tweet_Date__c, Tweet_ID__c 
                FROM Tweet__c 
                WHERE Tweet_Date__c != null
                AND Tweet_Title__c != null
                AND Tweet_Title__c != ''
                ORDER BY Tweet_Date__c DESC];
    }

    @AuraEnabled(cacheable=false)
    public static void getTweetToDelete(String tweetId) {
       try {
        Tweet__c tweetToDelete = [SELECT Id FROM Tweet__c WHERE Tweet_ID__c = :tweetId LIMIT 1];
       delete tweetToDelete;
       } catch (Exception e) {
        throw new AuraHandledException('Error in deleting tweet: ' + e.getMessage());
       }

    }
}